name: Spectral API Scan

on:
  push:

  pull_request:
    branches: [main]
  
  workflow_dispatch:


permissions: 
  contents: read
  security-events: write
  
jobs:
  spectral-lint:
    name: Spectral API Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7 

      - name: Set up Node.js
        uses: actions/setup-node@v7 
        with:
          node-version: '20'

      - name: Install Spectral and OWASP
        run: |
          npm init -y
          npm install @stoplight/spectral-cli @stoplight/spectral-owasp-ruleset

      - name: Run Spectral Scan
        continue-on-error: true
        run: |
            npx spectral lint openapi.json \
            --ruleset .spectral.yaml \
            --format json > spectral-results.json

      - name: Convertitore da json a sarif
        if: always()
        run: |
          python3 .github/scripts/create_report_spectral.py
      - name: Genera Report CSV
        if: always()
        run: |
          if [ -f spectral-results.sarif ]; then
            python3 -c "
          import json, csv

          with open('spectral-results.sarif', 'r') as f:
              sarif = json.load(f)

          with open('spectral-report.csv', 'w', newline='') as csv_file:
              writer = csv.writer(csv_file)
              writer.writerow(['Vulnerabilità', 'Gravità', 'Endpoint/URL', 'Messaggio/Descrizione'])

              for run in sarif.get('runs', []):
                  for res in run.get('results', []):
                      rule_id = res.get('ruleId', 'Unknown')
                      level = res.get('level', 'warning').upper()
                      message = res.get('message', {}).get('text', 'N/D')
                      
                      locs = res.get('locations', [{}])
                      phys_loc = locs[0].get('physicalLocation', {}) if locs else {}
                      file_path = phys_loc.get('artifactLocation', {}).get('uri', 'Sconosciuto')
                      
                      writer.writerow([rule_id, level, file_path, message])
          "
            echo "Report CSV di Spectral generato con successo!"
          else
            echo "Nessun file SARIF generato da Spectral."
          fi
  

      - name: Upload Spectral results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: spectral-results.sarif
          category: spectral-api-linting

      - name: Salva Report negli Artifatti
        if: always()
        uses: actions/upload-artifact@v7 
        with:
          name: spectral-security-reports
          path: |
            spectral-results.sarif
            spectral-report.csv